# Your presentation title
title:  Data as Commons

# Your presentation description (optional)
description: Course for the GSSI 

# Your name (optional)
author: Maurizio Napolitano <napolitano@fbk.eu>

# The Reveal theme
reveal_theme: night.css

# The Reveal transition
reveal_transition: slide 

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/ 

# Additional custom CSS paths
extra_css: 

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet: 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 

# Additional reveal.js dependencies
reveal_dependencies:

# Reveal.js subdirectory
reveal_path: reveal.js/

# mermaid.js diagram integration
mermaid_diagrams: true
mermaid_theme: dark # See https://mermaid-js.github.io/mermaid/#/theming?id=deployable-themes

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - LICENSE
  - README.md

# Don't change anything below
markdown: kramdown
highlighter: rouge
markdown_ext: ignoreme
